server:
  port: 8000
  servlet:
    context-path: /
# 数据源
spring:
  application:
    name: common
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/one?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# out sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mybatis plus
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: cn.newbeedaly.one.*.adaptor.*.entity

# FeignClient日志
logging:
  level:
    cn.newbeedaly.common.open: debug
